### ISSUE TITLE
로그인 페이지 제작

### ISSUE THREAD

**Issue by seoes** [new-wave-thug-life/exhibition-tracker-client#6]
로그인 페이지를 제작합니다

## 요구사항
- 라우팅 주소는 /login이어야 합니다.
- 로그인 위한 정보인 이메일, 비밀번호 칸이 존재해야 합니다.
- Input에 정보 입력 후 Button을 누르면, 정보들을 json 형식으로 POST방식 fetch하는 함수인 handleSubmit을 구현해야 합니다.
- form을 전송하는 시점에서 이메일 칸과 비밀번호 칸은 비어있으면 안되며, handleSubmit에서 fetch하기 전에 정규식으로 이메일, 비밀번호 값을 검사하여 만족여부를 판단후, 만족하지 못 한다면 fetch를 하지 않고 알림을 발생시켜야 합니다.
- 기본 이미지인 indigo-950 컬러를 메인 컬러로 사용해야 합니다.
- 첨부된 이미지를 참고하되, 디자인은 자유롭게 가능합니다. 다만 Select, Input, Button 컴포넌트를 생성하여 다른 페이지와 디자인적 통일성을 갖추어야 합니다.

## 참고 이미지
![](https://miro.medium.com/v2/resize:fit:1400/0*35U_QAmFXfxF18he.png)

**Comment by HJunSu** [comment]
thankyou sir

**Comment by seoes** [comment]
PR #9 에서 해결완료 @HJunSu
